correct regexp check

diff --git a/letsencrypt-renew b/letsencrypt-renew
--- a/letsencrypt-renew
+++ b/letsencrypt-renew
@@ -61,11 +61,11 @@ while getopts ":cfhs:" OPT; do
     s)
       # sleep x seconds - if x is an integer, else do nothing
       RE='^[0-9]+$'
-      if [[ "$OPTARG" =~ "${RE}" ]] ; then
+      if [[ "${OPTARG}" =~ ${RE} ]] ; then
         echo "Sleeping $OPTARG seconds..."
-        sleep $OPTARG
+        sleep ${OPTARG}
       else
-        echo "Invalid option: -$OPTARG is no Integer" >&2
+	echo "Invalid option: '${OPTARG}' is no Integer" >&2
         usage
       fi
       ;;
