fix integer check

diff --git a/letsencrypt-renew b/letsencrypt-renew
--- a/letsencrypt-renew
+++ b/letsencrypt-renew
@@ -69,12 +69,12 @@ while getopts ":cdfhs:" opt; do
   case "$opt" in
     s)
       # sleep x seconds - if x is an integer, else do nothing
-      re='^[0-9]+$'
-      if [[ "$OPTARG" =~ $re && "$DEBUG" == 1 ]] ; then
-        echo "Sleeping $OPTARG seconds..."
+        re="^[0-9]+$"
+	if [[ "$OPTARG" =~ $re ]] ; then
+        [[ "$DEBUG" == 1 ]] && echo "Sleeping $OPTARG seconds..."
         sleep $OPTARG
       else
-        echo "Invalid option: -$OPTARG is no Integer" >&2
+        echo "Invalid option: $OPTARG is no Integer" >&2
         usage
       fi
       ;;
@@ -190,4 +190,3 @@ for cert in $certs; do
     [ $DEBUG = 1 ] && echo -e "This certificate is currently not active. Skipping...\n"
   fi
 done
-
